export const GLOBAL_ENDPOINT = 'http://localhost:8080/'
export const AUTH_ENDPOINT = 'auth/'
export const CLIENTS_ENDPOINT = 'client/'
export const CONTRACTS_ENDPOINT = 'contract/'
export const CONSUMPTION_ENDPOINT = 'consumption/'
export const EXCHANGE_ENDPOINT = 'exchange/'
export const USER_ENDPOINT = 'user/'
